
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu May 11 12:39:19 GMT 2014
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BIT_INT = 19;
  public static final int RIGHT_BRACKET = 27;
  public static final int ASTERISK = 29;
  public static final int SLASH = 28;
  public static final int UMINUS = 39;
  public static final int PRIVATE = 3;
  public static final int FOR = 6;
  public static final int MINUS = 32;
  public static final int AND = 37;
  public static final int NOT = 36;
  public static final int OR = 38;
  public static final int COMMA = 22;
  public static final int LEFT_BRACE = 24;
  public static final int CLASS = 8;
  public static final int PLUS = 31;
  public static final int EXIT = 13;
  public static final int IF = 5;
  public static final int THIS = 7;
  public static final int DOT = 23;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int PLUS_PLUS = 30;
  public static final int TRUE = 10;
  public static final int SUPER = 12;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int SEMI_COLON = 21;
  public static final int NULL = 15;
  public static final int RIGHT_BRACE = 25;
  public static final int NUMBER = 40;
  public static final int VOID = 16;
  public static final int EQ = 35;
  public static final int NAME = 41;
  public static final int BIT_BOOLEAN = 20;
  public static final int PROTECTED = 4;
  public static final int NOT_EQ = 34;
  public static final int PUBLIC = 2;
  public static final int EXTENDS = 9;
  public static final int STRING = 42;
  public static final int FALSE = 11;
  public static final int LEFT_BRACKET = 26;
  public static final int PRINT = 14;
  public static final int EQ_EQ = 33;
}

